// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbbjxWXtipzEZKCXG7edaV77degvyyeto',
    appId: '1:952523339349:web:a9e3dc76040b1b2ea406dc',
    messagingSenderId: '952523339349',
    projectId: 'ngibrit-go',
    authDomain: 'ngibrit-go.firebaseapp.com',
    storageBucket: 'ngibrit-go.firebasestorage.app',
    measurementId: 'G-N13L3GC061',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDysL4PBO8BIm6kXBcc1uP8DA4A296Bz7s',
    appId: '1:952523339349:android:201ff719b1ecf391a406dc',
    messagingSenderId: '952523339349',
    projectId: 'ngibrit-go',
    storageBucket: 'ngibrit-go.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVCBdsZrMiRRUlIa2uLqd-d0IBsRFlX_s',
    appId: '1:952523339349:ios:b4f23a7b6e869f49a406dc',
    messagingSenderId: '952523339349',
    projectId: 'ngibrit-go',
    storageBucket: 'ngibrit-go.firebasestorage.app',
    iosBundleId: 'com.example.ngibritIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVCBdsZrMiRRUlIa2uLqd-d0IBsRFlX_s',
    appId: '1:952523339349:ios:b4f23a7b6e869f49a406dc',
    messagingSenderId: '952523339349',
    projectId: 'ngibrit-go',
    storageBucket: 'ngibrit-go.firebasestorage.app',
    iosBundleId: 'com.example.ngibritIn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbbjxWXtipzEZKCXG7edaV77degvyyeto',
    appId: '1:952523339349:web:606d390d1228d541a406dc',
    messagingSenderId: '952523339349',
    projectId: 'ngibrit-go',
    authDomain: 'ngibrit-go.firebaseapp.com',
    storageBucket: 'ngibrit-go.firebasestorage.app',
    measurementId: 'G-4PE0H7W5RJ',
  );
}
